In [1]:
import tensorflow as tf

In [2]:
X = tf.placeholder(tf.float32, [None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [3]:
x_data = [[1,2,3], [4,5,6]]

In [4]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [5]:
W = tf.Variable([[0.1, 0.1],[0.2, 0.2], [0.3, 0.3]])

In [6]:
expr = tf.matmul(X, W) + b

In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [8]:
print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]]
=== b ===
[[-0.05840694]
 [-0.2010647 ]]
=== expr ===
[[1.3415931 1.3415931]
 [2.9989352 2.9989352]]


In [9]:
sess.close()